
export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_SUCCESSFUL="LOGIN_SUCCESSFUL";
export const LOGIN_FAILURE="LOGIN_FAILURE";

export const GET_REQUEST = "GET_REQUEST";
export const GET_REQUEST_FAILURE = "GET_REQUEST_FAILURE";
export const GET_REQUEST_SUCCESS = "GET_REQUEST_SUCCESS";

export const TOGGLE_WISHLIST_SUCCESS = "TOGGLE_WISHLIST_SUCCESS"

export const TOGGLE_ADDTOCART_SUCCESS = "TOGGLE_ADDTOCART_SUCCESS"

export const SET_DATA_IN_LOCAL = "SET_DATA_IN_LOCAL"
export const SET_WISHLIST_DATA_IN_LOCAL = "SET_WISHLIST_DATA_IN_LOCAL"
export const SET_DELETED_DATA_IN_LOCAL = "SET_DELETED_DATA_IN_LOCAL"
export const SET_DELETED_WISHLIST_DATA_IN_LOCAL = "SET_DELETED_WISHLIST_DATA_IN_LOCAL"
export const GET_DATA_FROM_LOCAL = "GET_DATA_FROM_LOCAL"

export const SET_QUANTITY_IN_LOCAL = "SET_QUANTITY_IN_LOCAL"




