
export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_SUCCESSFUL="LOGIN_SUCCESSFUL";
export const LOGIN_FAILURE="LOGIN_FAILURE";

export const GET_REQUEST = "GET_REQUEST";
export const GET_REQUEST_FAILURE = "GET_REQUEST_FAILURE";
export const GET_REQUEST_SUCCESS = "GET_REQUEST_SUCCESS";
